# Generated by Django 4.1.3 on 2025-01-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the donor', max_length=100)),
                ('email', models.EmailField(help_text='Email address of the donor', max_length=254)),
                ('message', models.TextField(blank=True, help_text='Optional message from the donor', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Donation amount in USD', max_digits=10)),
            ],
        ),
    ]
