# Generated by Django 5.1.5 on 2025-02-04 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_volunteer_volunteerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
