# Generated by Django 5.1.5 on 2025-03-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
